name: "Run pre-commit"
description: "A composite action that sets up Rust and runs pre-commit"
author: "Andrew Aylett"
inputs:
  libs:
    description: 'Extra Libraries'
    required: false
    default: ''
runs:
  using: composite
  steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Dependencies
        if: input.libs != ''
        run: sudo apt install ${{ input.libs }}

      - uses: pre-commit/action@v3.0.1
